---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pe-frontend
  namespace: youlearn
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: pr-frontend
      containers:
      - image: samgiles/pe-fe:sha-ababe04
        name: pr-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yl-messaging
  namespace: youlearn
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: yl-messaging
      containers:
      - image: samgiles/yl-messaging:sha-6933aa7
        name: yl-messaging
