---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pe-frontend
  namespace: youlearn
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: pr-frontend
      containers:
      - image: samgiles/pe-fe:sha-1a05620
        name: pr-frontend
