apiVersion: v1
kind: Service
metadata:
  name: yl-headpose
  labels:
    app.kubernetes.io/name: yl-headpose
  namespace: youlearn
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  selector:
    app.kubernetes.io/name: yl-headpose
