apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
  name: yl-messaging
spec:
  rules:
  - host: messaging.youlearn.kontr.io
    http:
      paths:
      - backend:
          serviceName: yl-frontend
          servicePort: 9999
  tls:
  - hosts:
    -  messaging.youlearn.kontr.io
    secretName: youlearn-messaging-prod-cert

